# Generated by Django 3.1.7 on 2021-08-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210806_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='can_be_parent',
            field=models.BooleanField(default=False),
        ),
    ]
