# Generated by Django 3.1.7 on 2021-08-10 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0004_auto_20210809_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_identification',
            name='build_techniques',
            field=models.CharField(choices=[('aluminum extrusions', 'aluminum extrusions'), ('welding', 'welding'), ('carpentry', 'carpentry'), ('fiberglass', 'fiberglass'), ('CNC', 'CNC'), ('foam', 'foam')], max_length=20, verbose_name='Predominant build technique'),
        ),
        migrations.CreateModel(
            name='Vehicle_likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='website.vehicle_identification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
