# Generated by Django 3.1.7 on 2021-08-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210811_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='like_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
