# Generated by Django 3.1.7 on 2021-08-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210811_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/comment_pictures'),
        ),
        migrations.DeleteModel(
            name='Comment_pictures',
        ),
    ]
