# Generated by Django 3.1.7 on 2021-08-12 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20210811_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/comment_pictures'),
        ),
    ]
